/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _DetailRoute } from '../pages/detail';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/detail': ReturnType<typeof _DetailRoute.useParams>;
    '/': ReturnType<typeof _IndexRoute.useParams>;
  }
}
