/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _SharedRoute } from '../pages/shared';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/shared': ReturnType<typeof _SharedRoute.useParams>;
  }
}
