/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _InterstitialAdResultRoute } from '../pages/interstitial-ad-result';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/interstitial-ad-result': ReturnType<typeof _InterstitialAdResultRoute.useParams>;
  }
}
